# Generated by Django 4.1.2 on 2023-02-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
